/*

 MAP_PLUMVILLAGE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 20
   Tile set      : C:\gbdk\gbtd\Tileset_1.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Map_PlumVillageWidth 20
#define Map_PlumVillageHeight 20
#define Map_PlumVillageBank 0

#define Map_PlumVillage Map_PlumVillagePLN0
extern unsigned char Map_PlumVillagePLN0[];
extern unsigned char Map_PlumVillagePLN1[];

/* End of MAP_PLUMVILLAGE.H */
